# Day 2 Data wrangling with Python - Exercises with answers

## Exercise 1

#### Question 1
##### Create an array of 25 numbers between 1 and 100 (including 100) and save to `arr1` variable.
##### Pring the type and data type of `arr1`.

#### Answer:

In [1]:
import numpy as np

In [2]:
arr1 = np.linspace(1, 100, 25)
arr1

array([  1.   ,   5.125,   9.25 ,  13.375,  17.5  ,  21.625,  25.75 ,
        29.875,  34.   ,  38.125,  42.25 ,  46.375,  50.5  ,  54.625,
        58.75 ,  62.875,  67.   ,  71.125,  75.25 ,  79.375,  83.5  ,
        87.625,  91.75 ,  95.875, 100.   ])

In [3]:
print(type(arr1))

<class 'numpy.ndarray'>


In [4]:
print(arr1.dtype)

float64


#### Question 2
##### Create an array of 20 numbers from 50 to 70 (excluding 70).
##### Use `arange` function and assign the output to `arr2` variable.

#### Answer:

In [5]:
arr2 = np.arange(50, 70)
arr2

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69])

#### Question 3
##### Create an array of all even numbers between 30 and 60 (excluding 60).
##### Create an array of numbers between 0 and 100 (including 100), with step size of 25.

#### Answer:

In [6]:
np.arange(30, 60, 2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [7]:
np.arange(0, 101, 25)

array([  0,  25,  50,  75, 100])

#### Question 4
##### Create an array of 10 numbers between 0 and 20 (including 20) assign to `arr3` variable.
##### Use linspace function.
##### Find the max, min and sum of the array.

#### Answer:

In [8]:
arr3 = np.linspace(0, 20, 10)
arr3

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [9]:
np.amin(arr3)

0.0

In [10]:
np.amax(arr3)

20.0

In [11]:
np.sum(arr3)

100.0

#### Question 5
##### Create two arrays of size 4 with the numbers 4, 5, 6, 4 in `array1` and 7, 2, 12, 16 in `array2`.
##### Find the `sum`,  `product`, `difference` and `quotient` of `array1` and `array2` and save as `array_sum`, `product`, `difference`, and `quotient` variables respectively.
##### Print the results.

#### Answer:

In [12]:
array1 = np.array([4, 5, 6, 4])
array2 = np.array([7, 2, 12, 16])

In [13]:
array_sum = array1 + array2
print(array_sum)

[11  7 18 20]


In [14]:
product = array1 * array2
print(product)

[28 10 72 64]


In [15]:
difference = array1 - array2
print(difference)

[ -3   3  -6 -12]


In [16]:
quotient = array1 / array2
print(quotient)

[0.57142857 2.5        0.5        0.25      ]


## Exercise 2

#### Question 1
##### Compute the absolute value of each entry in the following array `[5, -8, -66, 4]` and assign it to `abs_values` variable. Print the result.
##### Print the length of the `abs_values` array.
##### Print the 3rd element of `abs_values`.

#### Answer:

In [17]:
abs_values = abs(np.array([5, -8, -66, 4]))

In [18]:
print(len(abs_values))

4


In [19]:
print(abs_values[2])

66


#### Question 2
##### Print all numbers greater than 25 in `abs_values` array.

#### Answer:

In [20]:
abs_values[abs_values > 25]

array([66])

#### Question 3
##### Create a matrix with 3 rows and assign to variable `mat1`.
- [4, 5, 6]
- [8, 3, 2]
- [6, 7, 3]

##### Find the shape of the matrix.

#### Answer:

In [21]:
mat1 = np.array([[4, 5, 6], [8, 3, 2], [6, 7, 3]])
mat1

array([[4, 5, 6],
       [8, 3, 2],
       [6, 7, 3]])

In [22]:
print(mat1.shape)

(3, 3)


#### Question 4
##### Find the value in the 2nd row and 3rd column.
##### Print the 2nd and 3rd rows.
##### Print the 1st column and rows up to the 2nd row.
##### Print all columns starting with column 2.

#### Answer:

In [23]:
print(mat1[1, 2])

2


In [24]:
print(mat1[1:, :])

[[8 3 2]
 [6 7 3]]


In [25]:
print(mat1[:2, 0])

[4 8]


In [26]:
print(mat1[:, 1:])

[[5 6]
 [3 2]
 [7 3]]


#### Question 5
##### Filter and print the elements greater than 5 in `mat1`.
##### Use a Boolean mask to filter all elements <= 5 and set them to 0.
##### Print the resulting matrix.

#### Answer:

In [27]:
print(mat1[mat1>5])

[6 8 6 7]


In [28]:
mat1[mat1<=5] = 0
print(mat1)

[[0 0 6]
 [8 0 0]
 [6 7 0]]


#### Question 6
##### Create a `numpy` array of 16 numbers between 10 and 25 (inclusive), and call it `arr4`. Use linspace function.
##### Reshape the array to a matrix of shape (4,4) and print it.
##### Reshape the array to a matrix with 8 rows and let Python infer the number of columns.

#### Answer:

In [29]:
arr4 = np.linspace(10,25,16)
arr4

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25.])

In [30]:
print(arr4.reshape(4,4))

[[10. 11. 12. 13.]
 [14. 15. 16. 17.]
 [18. 19. 20. 21.]
 [22. 23. 24. 25.]]


In [31]:
print(arr4.reshape(8,-1))

[[10. 11.]
 [12. 13.]
 [14. 15.]
 [16. 17.]
 [18. 19.]
 [20. 21.]
 [22. 23.]
 [24. 25.]]


#### Question 7
##### Import `pandas` as `pd` and `os` packages.
##### Set the working directory to data directory.
##### Print the working directory.

#### Answer:

In [32]:
import pandas as pd
import os

In [33]:
# Windows only.
main_dir = "C:/Users/[user_name]/Desktop/skill-soft"

In [34]:
# Mac only.
main_dir = "/Users/[username]/Desktop/skill-soft"

In [35]:
data_dir = main_dir + "/data/"

In [37]:
# Set working directory.
os.chdir(data_dir)

In [ ]:
# Check working directory.
print(os.getcwd())